log:
    level: WARNING

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"

providers:
    docker:
        exposedByDefault: false
        watch: true

api:
    dashboard: true
    debug: true
    insecure: true
